### ISSUE TITLE
style is not the same as assignment

### ISSUE THREAD

**Issue by Sara-Samer** [abdallahsellem/Bld.ai-pahse1-Task-#3]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/36432332/183972712-b84c6fa1-da10-49a2-ba6d-5ec5c0ae15b8.png">

**Comment by abdallahsellem** [comment]
how , at which part is not the same ?
![image](https://user-images.githubusercontent.com/77124997/183983834-f8859b34-63f0-401b-a1c5-05600de5751e.png)

**Comment by abdallahsellem** [comment]
you mean colors and fonts, bolds ... etc ?

**Comment by abdallahsellem** [comment]
Done, please review
